In [ ]:
# !pip install -U bitsandbytes datasets transformers accelerate peft trl evaluate rouge_score

In [1]:
import os
os.environ["PYTHONUTF8"] = "1"
# !pip install trl
import pandas as pd
import torch
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    BitsAndBytesConfig
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer
from huggingface_hub import login
import torch
import evaluate
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
#my token is :
#$env:HF_TOKEN="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"
# Paste your actual token inside the quotes below
login(token="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")

In [3]:
# train_data = pd.read_csv("/content/training_data.csv")
train_data_train = pd.read_csv("/content/training_data_train.csv")
train_data_test = pd.read_csv("/content/training_data_test.csv")
display(train_data_train.head(3))

,video_id,segment_index,n_segments,timestamp_start,timestamp_end,input,target_sentence,target_caption
0,v_QEdbqJijx1w,0,3,0.00,14.49,[0.0s] a woman sitting in front of a laptop co...,A woman is seen speaking to the camera while s...,A woman is seen speaking to the camera while s...
1,v_QEdbqJijx1w,1,3,15.25,44.61,[15.2s] a woman is sitting in front of a mirro...,She then holds up a contact lens and puts one ...,A woman is seen speaking to the camera while s...
2,v_QEdbqJijx1w,2,3,38.13,75.87,[38.1s] a woman in a black dress sitting at a ...,She puts another contact in her eye and smiles...,A woman is seen speaking to the camera while s...

In [ ]:
print("Train data columns : " ,  train_data_train.columns)
print("Train data train shape : " ,  train_data_train.shape)
print("Train data test shape : " ,  train_data_test.shape)
# print("Train data shape : " ,  train_data.shape)

Train data columns :  Index(['video_id', 'segment_index', 'n_segments', 'timestamp_start',
       'timestamp_end', 'input', 'target_sentence', 'target_caption'],
      dtype='object')
Train data train shape :  (1196, 8)
Train data test shape :  (309, 8)

In [ ]:
# Format the prompt using your specific columns
def format_instruction(row):
    # We wrap the 'input' and 'target_caption' in a consistent instruction template
    prompt = (
        "Below is a sequence of frame descriptions from a video. "
        "Write a cohesive caption summarizing the action.\n\n"
        f"### Descriptions:\n{row['input']}\n\n"
        f"### Caption:\n{row['target_caption']}"
    )
    return prompt
df_train = train_data_train.copy()
df_train['text'] = df_train.apply(format_instruction, axis=1)
train_dataset = Dataset.from_pandas(df_train[['text']])

In [ ]:
import torch
import gc
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTConfig, SFTTrainer

# --- CLEAR MEMORY ---
gc.collect()
torch.cuda.empty_cache()
# ---------------------

model_id = "Qwen/Qwen2.5-7B-Instruct"

# ---------------------------------------------------------
# 1. LOAD THE BASE MODEL
# ---------------------------------------------------------
print("Loading Base Model...")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    torch_dtype=torch.float16,
    device_map={"": 0}           # Safely forces model onto T4 GPU
)

model.gradient_checkpointing_enable()
model = prepare_model_for_kbit_training(model)

# ---------------------------------------------------------
# 2. ATTACH THE ADAPTERS & CAST
# ---------------------------------------------------------
print("Attaching LoRA Adapters...")
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"]
)

model = get_peft_model(model, peft_config)

# The ultimate safety net: force all trainable weights to standard float32
for name, param in model.named_parameters():
    if param.requires_grad:
        param.data = param.data.to(torch.float32)

Loading Base Model...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

Attaching LoRA Adapters...

In [ ]:
# ---------------------------------------------------------
# 3. CONFIGURE AND START TRAINING
# ---------------------------------------------------------
print("Preparing Trainer...")
training_args = SFTConfig(
    output_dir="./video_caption_checkpoints",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=1e-4,
    num_train_epochs=3,
    logging_steps=10,
    optim="paged_adamw_32bit",
    save_strategy="epoch",
    bf16=False,
    fp16=False,
    report_to="none",
    dataset_text_field="text",
    max_length=512               # <--- THE FINAL FIX: Renamed from max_seq_length!
)

trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    args=training_args,
)


print("Starting training! Let's go!")
trainer.train()

Preparing Trainer...

Adding EOS to train dataset:   0%|          | 0/1196 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1196 [00:00<?, ? examples/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Starting training! Let's go!

TrainOutput(global_step=225, training_loss=1.3873908763461642, metrics={'train_runtime': 3684.6568, 'train_samples_per_second': 0.974, 'train_steps_per_second': 0.061, 'total_flos': 3.61719572315136e+16, 'train_loss': 1.3873908763461642})

Saving model so we can use it later

In [ ]:
trainer.save_model("./video_caption_model")

In [ ]:
tokenizer.save_pretrained("./video_caption_model")

('./video_caption_model/tokenizer_config.json',
 './video_caption_model/chat_template.jinja',
 './video_caption_model/tokenizer.json')

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("./video_caption_model")
tokenizer = AutoTokenizer.from_pretrained("./video_caption_model")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Exporting the model

In [ ]:
# import shutil
# from google.colab import files

# # Path to the directory you want to download
# local_model_path = "./video_caption_model"
# zip_file_name = "video_caption_model.zip"

# # Create a zip archive of the directory
# shutil.make_archive(zip_file_name.replace('.zip', ''), 'zip', local_model_path)

# # Download the zip file
# files.download(zip_file_name)

In [ ]:
# import shutil
# from google.colab import files

# # Define paths for checkpoint 225
# checkpoint_folder = './video_caption_checkpoints/checkpoint-225'
# zip_filename = 'video_caption_checkpoint_225'

# print(f'Zipping {checkpoint_folder}...')
# # Create zip file
# shutil.make_archive(zip_filename, 'zip', checkpoint_folder)

# print(f'Downloading {zip_filename}.zip...')
# # Download to local machine
# files.download(f'{zip_filename}.zip')

Zipping ./video_caption_checkpoints/checkpoint-225...
Downloading video_caption_checkpoint_225.zip...

#testing data - model evaluation with Huggingface rouge metrics.

In [ ]:
import torch
import evaluate
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel

# ==========================================
# 1. LOAD THE BASE MODEL TO GPU
# ==========================================
print("1. Loading base model to GPU...")
model_id = "Qwen/Qwen2.5-7B-Instruct"

# 4-bit config safe for the free T4 GPU
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    torch_dtype=torch.float16,
    device_map={"": 0}          # Forces model to GPU
)

# ==========================================
# 2. ATTACH YOUR SAVED CHECKPOINT
# ==========================================
print("2. Attaching your trained LoRA weights...")
# Ensure this path matches exactly where your checkpoint is saved!
checkpoint_path = "./video_caption_checkpoints/checkpoint-225"

model = PeftModel.from_pretrained(base_model, checkpoint_path)
model.eval() # Put model strictly in test/read-only mode

# ==========================================
# 3. SETUP THE TEST DATAFRAME
# ==========================================
print("\n3. Prepping evaluation data...")
DESCRIPTION_COLUMN = "input"
TARGET_COLUMN = "target_caption"

# Sampling 50 videos for a quick test. Remove .sample(50) to run all 309!
test_df = training_data_test.sample(50, random_state=42)
rouge = evaluate.load('rouge')

predictions = []
references = []

# ==========================================
# 4. GENERATE CAPTIONS
# ==========================================
print(f"Generating captions for {len(test_df)} videos...")

for index, row in tqdm(test_df.iterrows(), total=len(test_df)):

    prompt = (
        "Below is a sequence of frame descriptions from a video. "
        "Write a cohesive caption summarizing the action.\n\n"
        f"### Descriptions:\n{row[DESCRIPTION_COLUMN]}\n\n"
        f"### Caption:\n"
    )

    # Tokenize the text
    inputs = tokenizer(prompt, return_tensors="pt")

    # Force every tensor in the dictionary to the exact same GPU as the model
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model.generate(**inputs, max_new_tokens=50, temperature=0.7)

    result = tokenizer.decode(outputs[0], skip_special_tokens=True)
    generated_caption = result.split("### Caption:\n")[-1].strip()

    predictions.append(generated_caption)
    references.append(row[TARGET_COLUMN])

# ==========================================
# 5. SCORE AND PLOT THE CHART
# ==========================================
print("\n4. Calculating ROUGE metrics...")
results = rouge.compute(predictions=predictions, references=references)

scores = [
    results['rouge1'] * 100,
    results['rouge2'] * 100,
    results['rougeL'] * 100
]
labels = ['ROUGE-1\n(Word Match)', 'ROUGE-2\n(Phrase Match)', 'ROUGE-L\n(Sentence Flow)']

plt.figure(figsize=(9, 5.5))
ax = sns.barplot(x=labels, y=scores, palette="mako")

plt.title("Model Performance vs. Human Captions", fontsize=16, fontweight='bold', pad=15)
plt.ylabel("Score (0 to 100)", fontsize=12, fontweight='bold')
plt.ylim(0, max(scores) + 20)

for i, v in enumerate(scores):
    ax.text(i, v + 2, f"{v:.1f}", ha='center', fontweight='bold', fontsize=12)

sns.despine()
plt.tight_layout()
plt.show()

print("\n" + "="*50)
print("SAMPLE GENERATIONS (THE VIBE CHECK)")
print("="*50)
for i in range(3):
    print(f"\n🎥 VIDEO {i+1}")
    print(f"True Caption: {references[i]}")
    print(f" Model Output: {predictions[i]}")